name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          git clone https://github.com/KatsiarynaMizhuryna/AT-in-JS-Practice.git
          cd AT-in-JS-Practice
          npm ci

      - name: Run UI tests with Cucumber
        env:
          HEADLESS: "true"
        run: |
          cd AT-in-JS-Practice
          npm run test:cucumber || true
          pkill -f chromedriver || true
          pkill -f chrome || true

      - name: Run Mocha tests
        run: |
          cd AT-in-JS-Practice
          npm run test:mocha

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          git clone https://github.com/KatsiarynaMizhuryna/AT-in-JS-Practice.git
          cd AT-in-JS-Practice
          npm ci

      - name: Run API tests
        env:
          HEADLESS: "true"
        run: |
          cd AT-in-JS-Practice
          npm run test:axios
