name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: AT-in-JS-Practice

      - name: Run UI tests with Cucumber
        env:
          HEADLESS: "true"
        run: npm run test:cucumber
        working-directory: AT-in-JS-Practice

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: AT-in-JS-Practice

      - name: Run API tests
        env:
          HEADLESS: "true"
        run: npm run test:axios
        working-directory: AT-in-JS-Practice
